/**
 * Offloading
 * Semester project for 7th semester at Aalborg University
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param jobId 
 * @param file 
 */
data class Assignment (

    val jobId: kotlin.Long? = null,
    val file: kotlin.Array<kotlin.Byte>? = null
) {
}