/**
 * Offloading
 * Semester project for 7th semester at Aalborg University
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param name 
 * @param jobpath 
 * @param timestamp 
 * @param status 
 * @param employer 
 * @param workersRequested 
 * @param workersAssigned 
 */
data class Job (

    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val jobpath: kotlin.String? = null,
    val timestamp: kotlin.Long? = null,
    val status: kotlin.String? = null,
    val employer: kotlin.String? = null,
    val workersRequested: kotlin.Int? = null,
    val workersAssigned: kotlin.Int? = null
) {
}