/**
 * Offloading
 * Semester project for 7th semester at Aalborg University
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param username 
 * @param password 
 */
data class UserCredentials (

    val username: kotlin.String? = null,
    val password: kotlin.String? = null
) {
}