/**
* Offloading
* Semester project for 7th semester at Aalborg University
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param username 
 * @param password 
 */

data class UserCredentials (
    @Json(name = "username")
    val username: kotlin.String? = null,
    @Json(name = "password")
    val password: kotlin.String? = null
)

